defaults:
  - override sweeper: optuna
  - override sweeper/sampler: tpe

run:
  dir: ${oc.env:ALTEXPDIR, experiments}/${dataset.name}/${exp_params.exp_name}/optuna_runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: ${oc.env:ALTEXPDIR, experiments}/${dataset.name}/${exp_params.exp_name}/optuna_runs/${now:%Y-%m-%d}/${now:%H-%M-%S} #
  subdir: ${hydra.job.num}
job:
  env_set:
    CUDA_VISIBLE_DEVICES: 3 # If working on a GPU machine with multiple users, it is recommended to set the GPU device to reduce the risk of conflicts
launcher:
  _target_: hydra_plugins.hydra_ray_launcher.ray_launcher.RayLauncher
  ray:
    init:
      num_gpus: 1
      num_cpus: 4

sweeper:
  sampler:
    seed: Null
    _target_: optuna.samplers.TPESampler
    consider_magic_clip: true
    consider_endpoints: false
    n_startup_trials: 100
    n_ei_candidates: 100
    multivariate: true
    #group: true
    warn_independent_sampling: true
    #consider_liar: true
  _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
  direction: maximize
  n_trials: 500
  n_jobs: 2 
  storage: "sqlite:///${oc.env:ALTEXPDIR, experiments}/optuna_results.sqlite3" # 
  study_name:  Test # Name of the study. If there are multiple studies in the same database, the study name must be unique. Otherwise, the existing study will be resumed.
  params: ???
