run:
  dir: ${oc.env:ALTEXPDIR, experiments}/${dataset.name}/${exp_params.exp_name}${oc.env:EXP_SPEC, ""}/${exp_params.goal_type}/singleruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: ${oc.env:ALTEXPDIR, experiments}/${dataset.name}/${exp_params.exp_name}${oc.env:EXP_SPEC, ""}/${exp_params.goal_type}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S} #
  subdir: ${hydra.job.num}
job:
  env_set:
    CUDA_VISIBLE_DEVICES: 0,1 # If working on a GPU machine with multiple users, it is recommended to set the GPU device to reduce the risk of conflicts
launcher:
  _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
  n_jobs: 2
  # ray:
  #   init:
  #     num_cpus: 5 # The number of CPUs corresponds to the number of workers
sweeper:
  params:
    # parameters to sweep